Repository opsw-4team/RimcMon, pull requests merged in 2024-12, with the labels that each got.

#12 #9 [Feat] 데이터베이스 연결 및 데이터 삽입 & 요청 코드 추가, 데이터 및 압축 이미지 삭제(Reset) 기능 추가
  Crawler.py
  PHP_Script/ truncate_crawl_data.php
  PHP_Script/insert_into_crawl_data.php
  PHP_Script/select_from_crawl_data.php
  Python_Script/insert_to_db.py
  Python_Script/reset_data.py
  Python_Script/select_from_db.py
  test.py
Labels: ⚒️ Feature

#14 #13 [Feat] 프론트 Streamlit 작업
  app.py
  logo/RimcMonlogo.png
Labels: ⚒️ Feature, Frontend

#21 #20 [Fix] 이미지 파일 경로 이탈 Error 로 인한 코드 수정
  RMC_Board.py
Labels: 🚨 Error, Frontend, ⚙ Setting

#28 #27[Fix] 간단한 오류 및 속성 수정
  RMC_Board.py
  TEST/rendering_test.py
Labels: 🚨 Error

#19 #18 [Feat] 사용자 정보 DB 저장, 데이터 요청 및 업데이트
  PHP_Script_Profile/insert_into_user_data.php
  PHP_Script_Profile/select_from_user_data.php
  PHP_Script_Profile/update_user_data.php
  Profile_BE/user_model.py
  Python_Script_Profile/insert_to_db.py
  Python_Script_Profile/select_from_db.py
  Python_Script_Profile/update_user_data.py
Labels: ⚒️ Feature, 💻 Testing, Backend

#24 #22[Feat] 프론트 파일 생성 및 작업
  Front/board.py
  Front/club.py
  Front/competition.py
  Front/img/림크몬.png
  Front/main.py
  Front/recruitment.py
  Front/study.py
Labels: ⚒️ Feature, Frontend, ⚙ Setting

#26 #25 [Feat] 프론트 로그인, 사용자 등록 페이지 구현
  Front/mainpage/board.py
  Front/mainpage/club.py
  Front/mainpage/competition.py
  Front/mainpage/main.py
  Front/mainpage/recruitment.py
  Front/mainpage/study.py
  Front/profilepage/profile.py
  Front/profilepage/user.py
  RMC_Board.py
  static/logo/RimcMonlogo.png
Labels: ⚒️ Feature, Frontend

#32 #31 [Feat] 관리자 대쉬보드 페이지 프론트 개발 및 백엔드 연동
  Front/manage/manage.py
  PHP_Script_Manage/delete_crawl_data.php
  PHP_Script_Manage/delete_user_data_manage.php
  PHP_Script_Manage/update_crawl_data.php
  PHP_Script_Manage/update_user_data_manage.php
  Python_Script_Manage/select_from_db.py
Labels: ⚒️ Feature, Backend, Frontend

#36 #35[Fix]프론트 - 화면전환 시 버튼 클릭 두 번 해야 하던 버그 수정
  Front/mainpage/board.py
  Front/mainpage/club.py
  Front/mainpage/competition.py
  Front/mainpage/main.py
  Front/mainpage/recruitment.py
  Front/mainpage/study.py
Labels: 📢 Issue, Frontend

#41 #39 [Docs] README.md 기능소개 및 수정
  README.md
Labels: ✏️ Documentation

#40 #29 [Feat] 공모전 실제 모집 페이지 경로 추출
  Crawling/Crawler.py
  Crawling/LinkCrawler.py
  PHP_Script/insert_into_crawl_data.php
  PHP_Script/select_from_crawl_data.php
  Python_Script/insert_to_db.py
Labels: ⚒️ Feature, Backend

#38 #32 [Design] 팀원 모집 페이지 프론트 작업
  Front/mainpage/board.py
  Front/mainpage/main.py
Labels: Frontend

#43 #42 [Fix] 사용자 정보 처리 관련 스크립트 수정
  Python_Script_Profile/insert_to_db.py
  Python_Script_Profile/select_from_db.py
  Python_Script_Profile/update_user_data.py
Labels: 💻 Testing, Backend

#44 #30 [Feat] 사용자 등록 프론트 DB 연결
  Front/profilepage/profile.py
  Front/profilepage/user.py
Labels: ⚒️ Feature, 💻 Testing, Frontend

#47 #46 [Feat] 메인 페이지 사이드바에서 로그인창 으로 넘어가게 구현 및 전체적인 페이지 수정
  Front/mainpage/board.py
  Front/mainpage/club.py
  Front/mainpage/competition.py
  Front/mainpage/main.py
Labels: ⚒️ Feature, Frontend

#48 #45[Feat] 관리자 페이지에서 크롤링 및 데이터 삭제 기능 추가
  Front/manage/manage.py
  Python_Script/insert_to_db.py
  Python_Script/reset_data.py
Labels: ⚒️ Feature, Backend, Frontend

#50 #49 [Feat] 게시글 데이터 삽입 및 조회를 위한 PHP 스크립트 추가
  PHP_Script_Posts/insert_into_post_data.php
  PHP_Script_Posts/select_from_post_data.php
  Python_Script_Posts/insert_to_db.py
  Python_Script_Posts/select_from_db.py
  TEST/posts_test.py
Labels: ⚒️ Feature, Backend

#54 #51 [Feat] 게시물 페이지 프론트 작업
  Front/mainpage/competition.py
  Front/mainpage/main.py
  Front/mainpage/post.py
  Front/profilepage/user.py
Labels: ⚒️ Feature, Frontend

#56 #55 [Docs] README.md 기능부분 수정
  README.md
Labels: ✏️ Documentation
